"use client";
import {useEffect,useState,type FormEvent} from "react";

type Bank={name:string;code:string;supportedTypes:string[]};
export default function PayoutSetup(){
 const [banks,setBanks]=useState<Bank[]>([]);const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 const [bankCode,setBankCode]=useState(""); const selected=banks.find(b=>b.code===bankCode);
 useEffect(()=>{fetch("/api/payouts/banks").then(r=>r.json()).then(d=>{if(d.banks)setBanks(d.banks);else setMsg(d.error||"Unable to load banks")}).catch(()=>setMsg("Unable to load banks"))},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const fd=new FormData(e.currentTarget);const body={bankCode,bankName:selected?.name,accountName:fd.get("accountName"),accountNumber:fd.get("accountNumber"),accountType:fd.get("accountType"),documentType:fd.get("documentType"),documentNumber:fd.get("documentNumber")};const r=await fetch("/api/payouts/setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setBusy(false);setMsg(r.ok?`Verified ✓ ${d.bankName} ••••${d.accountLast4}${d.securityHoldUntil?" — payouts temporarily held after this bank-detail change.":""}`:d.error||"Verification failed")}
 return <form className="card" onSubmit={submit}><h2>Set up weekly payouts</h2><p>RealSign sends these details securely to the payment provider for validation. Your full bank account and identity number are not stored in the RealSign payout table.</p><label>Bank<select className="field" value={bankCode} onChange={e=>setBankCode(e.target.value)} required><option value="">Select bank</option>{banks.map(b=><option value={b.code} key={b.code}>{b.name}</option>)}</select></label><label>Account holder name<input className="field" name="accountName" required/></label><label>Account number<input className="field" name="accountNumber" inputMode="numeric" autoComplete="off" required/></label><label>Account type<select className="field" name="accountType" required><option value="personal">Personal</option>{selected?.supportedTypes?.includes("business")?<option value="business">Business</option>:null}</select></label><label>Verification document<select className="field" name="documentType" required><option value="identityNumber">South African ID number</option><option value="passportNumber">Passport number</option><option value="businessRegistrationNumber">Business registration number</option></select></label><label>Document number<input className="field" name="documentNumber" autoComplete="off" required/></label><button className="btn" disabled={busy||!bankCode}>{busy?"Verifying…":"Verify payout account"}</button>{msg?<p className="notice">{msg}</p>:null}</form>
}
