"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {serviceLabel} from "@/lib/marketplace";
export default function InterpreterRequestForm({providerId,services}:{providerId:string;services:any[]}){
 const router=useRouter();const [busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function submit(e:any){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const body={providerId,serviceId:f.get("serviceId"),mode:f.get("mode"),startAt:new Date(String(f.get("startAt"))).toISOString(),location:f.get("location"),context:f.get("context"),note:f.get("note")};const r=await fetch("/api/interpreter-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setMsg(d.error||"Unable to send request");setBusy(false);return}router.push("/bookings");router.refresh()}
 return <form className="card form-grid" onSubmit={submit}><h2>Request this interpreter</h2><label>Service<select name="serviceId" required>{services.map(s=><option value={s.id} key={s.id}>{serviceLabel(s)} · {s.duration_min} min</option>)}</select></label><label>Mode<select name="mode"><option value="remote">Remote</option><option value="in_person">In person</option></select></label><label>Date and time<input name="startAt" type="datetime-local" required/></label><label>Location for in-person work<input name="location" placeholder="Venue / town / address"/></label><label>Context<select name="context"><option>general</option><option>medical</option><option>education</option><option>employment</option><option>business</option><option>government</option><option>legal</option><option>event</option></select></label><label>Anything useful for the interpreter?<textarea name="note" maxLength={1500} placeholder="Do not include unnecessary confidential medical or legal details."/></label><button className="btn" disabled={busy}>{busy?"Sending…":"Send request"}</button>{msg?<p className="notice">{msg}</p>:null}</form>
}
