export type HelpContentItem = {
  id: string;
  slug: string;
  title: string;
  text_explanation: string;
  audience: string[];
  screen_key: string;
  placement_key: string;
  active: boolean;
  video_path: string | null;
};

// These entries mirror the app's built-in fallback help. Admin can publish an
// editable database version by saving any one of them.
export const DEFAULT_HELP_CONTENT: HelpContentItem[] = [
  { id: "default:what-is-realsign", slug: "what-is-realsign", title: "What is RealSign?", text_explanation: "RealSign connects learners with Deaf SASL tutors and South African Sign Language interpreters for lessons and video calls.", audience: ["everyone"], screen_key: "home", placement_key: "what-is-realsign", active: true, video_path: null },
  { id: "default:account-access", slug: "account-access", title: "Account access help", text_explanation: "Create an account, sign in, request a password reset, or confirm your email address to use RealSign.", audience: ["everyone"], screen_key: "general", placement_key: "account-access", active: true, video_path: null },
  { id: "default:password-reset", slug: "password-reset", title: "Password reset help", text_explanation: "Use the newest password reset email on this device. The link must open a secure recovery session before a new password can be saved.", audience: ["everyone"], screen_key: "general", placement_key: "password-reset", active: true, video_path: null },
  { id: "default:marketplace", slug: "marketplace", title: "Marketplace help", text_explanation: "Choose a language and review approved provider profiles. Open a profile to see services, prices and available booking times.", audience: ["learner"], screen_key: "booking", placement_key: "marketplace", active: true, video_path: null },
  { id: "default:provider-profile", slug: "provider-profile", title: "Provider profile help", text_explanation: "Review this provider's introduction, languages, services, prices and available booking times before choosing a service.", audience: ["learner"], screen_key: "booking", placement_key: "provider-profile", active: true, video_path: null },
  { id: "default:booking-time", slug: "booking-time", title: "Booking time help", text_explanation: "Choose an available date and time, select the lesson or interpreting service you want, then continue to confirm and pay.", audience: ["learner"], screen_key: "booking", placement_key: "booking-time", active: true, video_path: null },
  { id: "default:manage-booking", slug: "manage-booking", title: "Manage booking help", text_explanation: "Review your booking details, messages and session access from this page.", audience: ["everyone"], screen_key: "booking", placement_key: "manage-booking", active: true, video_path: null },
  { id: "default:learner-languages", slug: "learner-languages", title: "Learner language help", text_explanation: "Choose the spoken language you prefer for written communication and whether you would like SASL help where it is available.", audience: ["learner"], screen_key: "general", placement_key: "learner-languages", active: true, video_path: null },
  { id: "default:account", slug: "account", title: "Account help", text_explanation: "Update your username, request a password reset, or sign out of RealSign from this section.", audience: ["everyone"], screen_key: "general", placement_key: "account", active: true, video_path: null },
  { id: "default:my-bookings", slug: "my-bookings", title: "My bookings help", text_explanation: "View your upcoming and completed lessons, including booking details and session access.", audience: ["everyone"], screen_key: "booking", placement_key: "my-bookings", active: true, video_path: null },
  { id: "default:push-reminders", slug: "push-reminders", title: "Push reminders help", text_explanation: "Manage booking reminders and visual push alerts so important updates are easier to notice.", audience: ["everyone"], screen_key: "general", placement_key: "push-reminders", active: true, video_path: null },
  { id: "default:realsign-help", slug: "realsign-help", title: "RealSign help", text_explanation: "Open short RealSign help explanations with matching text and SASL videos when they are available.", audience: ["everyone"], screen_key: "general", placement_key: "realsign-help", active: true, video_path: null },
  { id: "default:dictionary", slug: "dictionary", title: "Dictionary help", text_explanation: "Search for an English word to find the matching RealSASL sign video and explanation.", audience: ["everyone"], screen_key: "general", placement_key: "dictionary", active: true, video_path: null },
  { id: "default:session-help", slug: "session-help", title: "Session help", text_explanation: "Use this secure video room for the confirmed RealSign booking. Only the learner and provider can join.", audience: ["everyone"], screen_key: "video", placement_key: "session-help", active: true, video_path: null },
  { id: "default:provider-dashboard", slug: "provider-dashboard", title: "Provider dashboard help", text_explanation: "Use the provider tools to manage your profile, lesson guides, availability, payouts and earnings.", audience: ["provider"], screen_key: "provider", placement_key: "provider-dashboard", active: true, video_path: null },
  { id: "default:provider-application", slug: "provider-application", title: "Provider application help", text_explanation: "Complete this application to offer SASL tutoring, SASL interpreting, or both. Provider approval is required before learners can book you.", audience: ["provider"], screen_key: "provider", placement_key: "provider-application", active: true, video_path: null },
  { id: "default:provider-roles", slug: "provider-roles", title: "Provider roles help", text_explanation: "Choose whether you want to teach SASL, interpret SASL, or offer both services. RealSign applies separate approval rules where needed.", audience: ["provider"], screen_key: "provider", placement_key: "provider-roles", active: true, video_path: null },
  { id: "default:provider-verification", slug: "provider-verification", title: "Verification help", text_explanation: "Upload the documents required for the provider role you selected. RealSign Admin reviews each file before approving the application.", audience: ["provider"], screen_key: "provider", placement_key: "provider-verification", active: true, video_path: null },
  { id: "default:provider-introduction", slug: "provider-introduction", title: "Provider introduction help", text_explanation: "Add the name and introduction that learners will see on your provider profile. An introduction video helps learners understand who they may book.", audience: ["provider"], screen_key: "provider", placement_key: "provider-introduction", active: true, video_path: null },
  { id: "default:provider-services-rates", slug: "provider-services-rates", title: "Lessons, interpreting and rates help", text_explanation: "Choose a service or lesson guide, select a duration, and set a price within the allowed range. You can update or remove active services later.", audience: ["provider"], screen_key: "provider", placement_key: "provider-services-rates", active: true, video_path: null },
  { id: "default:provider-booking-preferences", slug: "provider-booking-preferences", title: "Booking preferences help", text_explanation: "Set how much notice you need before a booking and the minimum break between sessions. RealSign uses these settings to protect your time.", audience: ["provider"], screen_key: "provider", placement_key: "provider-booking-preferences", active: true, video_path: null },
  { id: "default:provider-submit", slug: "provider-submit", title: "Submit help", text_explanation: "Submit when your provider profile, verification, introduction, services, and availability are ready. RealSign Admin reviews the application before learners can book you.", audience: ["provider"], screen_key: "provider", placement_key: "provider-submit", active: true, video_path: null },
  { id: "default:provider-availability", slug: "provider-availability", title: "Availability help", text_explanation: "Turn on the regular time windows when learners may book you. Use 15-minute time steps, and switch a window off when you are not available.", audience: ["provider"], screen_key: "provider", placement_key: "provider-availability", active: true, video_path: null },
  { id: "default:provider-lesson-guides", slug: "provider-lesson-guides", title: "Lesson guides help", text_explanation: "Browse the built-in lesson topics and choose one when adding a service. Learners will see the topic you publish.", audience: ["provider"], screen_key: "provider", placement_key: "provider-lesson-guides", active: true, video_path: null },
  { id: "default:provider-languages", slug: "provider-languages", title: "Provider languages help", text_explanation: "Choose the languages you can use for teaching or interpreting. A language choice describes communication ability and does not mean you hear or speak the language.", audience: ["provider"], screen_key: "provider", placement_key: "provider-languages", active: true, video_path: null },
  { id: "default:provider-payout-setup", slug: "provider-payout-setup", title: "Payout setup help", text_explanation: "Verify the bank account that RealSign will use for provider payouts. You can return here later to review the payout account.", audience: ["provider"], screen_key: "provider", placement_key: "provider-payout-setup", active: true, video_path: null },
  { id: "default:provider-earnings", slug: "provider-earnings", title: "Provider earnings help", text_explanation: "Review earnings from completed bookings, including pending and available amounts and payout history.", audience: ["provider"], screen_key: "provider", placement_key: "provider-earnings", active: true, video_path: null },
  { id: "default:identity-verified", slug: "identity-verified", title: "Identity Verified help", text_explanation: "RealSign Admin has reviewed this provider's identity document.", audience: ["learner"], screen_key: "booking", placement_key: "identity-verified", active: true, video_path: null },
  { id: "default:deaf-verified", slug: "deaf-verified", title: "Deaf Verified help", text_explanation: "RealSign Admin has reviewed the provider's Deaf verification.", audience: ["learner"], screen_key: "booking", placement_key: "deaf-verified", active: true, video_path: null },
  { id: "default:teacher-qualification", slug: "teacher-qualification", title: "Teacher qualification help", text_explanation: "RealSign Admin has reviewed this provider's teaching qualification.", audience: ["learner"], screen_key: "booking", placement_key: "teacher-qualification", active: true, video_path: null },
  { id: "default:interpreter-verified", slug: "interpreter-verified", title: "Interpreter Verified help", text_explanation: "RealSign Admin has reviewed this provider's interpreter assessment.", audience: ["learner"], screen_key: "booking", placement_key: "interpreter-verified", active: true, video_path: null }
];
