"use client";
import {useEffect,useRef,useState} from "react";
import BookingChat from "./BookingChat";
import DictionarySearch from "@/components/dictionary/DictionarySearch";

type MeetingInfo={roomUrl:string;token:string;booking:{id:string;reference:string;startAt:string;endAt:string;wrapUpMinutes:number};participantRole:"learner"|"provider";displayName:string};
function attach(video:HTMLVideoElement|null,participant:any,muted=false){if(!video||!participant)return;const tracks=[participant.tracks?.video?.persistentTrack||participant.tracks?.video?.track,participant.tracks?.audio?.persistentTrack||participant.tracks?.audio?.track].filter(Boolean);const stream=new MediaStream(tracks);if(video.srcObject!==stream)video.srcObject=stream;video.muted=muted;video.play().catch(()=>{})}
export default function MeetRoom({bookingId,currentUserId}:{bookingId:string;currentUserId:string}){
 const [phase,setPhase]=useState<"preview"|"joining"|"call"|"ended">("preview"),[previewOk,setPreviewOk]=useState(false),[meeting,setMeeting]=useState<MeetingInfo|null>(null),[error,setError]=useState(""),[network,setNetwork]=useState("good"),[remoteName,setRemoteName]=useState("Other person"),[remaining,setRemaining]=useState<number|null>(null),[showQuickProblem,setShowQuickProblem]=useState(false),[showDictionary,setShowDictionary]=useState(false),[cameraOn,setCameraOn]=useState(true),[micOn,setMicOn]=useState(true);
 const previewRef=useRef<HTMLVideoElement>(null),localRef=useRef<HTMLVideoElement>(null),remoteRef=useRef<HTMLVideoElement>(null),previewStream=useRef<MediaStream|null>(null),callRef=useRef<any>(null),joinedOnce=useRef(false),reportedNetwork=useRef("");
 async function log(eventType:string,details:any={}){fetch(`/api/bookings/${bookingId}/technical-event`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventType,details})}).catch(()=>{})}
 useEffect(()=>{let active=true;navigator.mediaDevices?.getUserMedia({video:true,audio:true}).then(s=>{if(!active){s.getTracks().forEach(t=>t.stop());return}previewStream.current=s;if(previewRef.current){previewRef.current.srcObject=s;previewRef.current.muted=true;previewRef.current.play().catch(()=>{})}setPreviewOk(true)}).catch(()=>setError("Camera or microphone permission is needed before joining."));return()=>{active=false;previewStream.current?.getTracks().forEach(t=>t.stop())}},[]);
 useEffect(()=>{if(!meeting)return;const end=new Date(meeting.booking.endAt).getTime(),wrap=meeting.booking.wrapUpMinutes*60000;const tick=()=>{const now=Date.now();setRemaining(Math.ceil((end-now)/1000));if(now>=end+wrap&&phase==="call"){callRef.current?.leave();fetch(`/api/bookings/${bookingId}/complete`,{method:"POST"}).catch(()=>{});setPhase("ended")}};tick();const t=setInterval(tick,1000);return()=>clearInterval(t)},[meeting,bookingId,phase]);
 async function join(){setError("");setPhase("joining");previewStream.current?.getTracks().forEach(t=>t.stop());try{const r=await fetch(`/api/bookings/${bookingId}/meeting`,{method:"POST"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to join");setMeeting(j);const Daily=(await import("@daily-co/daily-js")).default;const call=Daily.createCallObject({subscribeToTracksAutomatically:true});callRef.current=call;const render=()=>{const parts=call.participants();const local=parts.local;const remote=Object.values(parts).find((p:any)=>!p.local) as any;attach(localRef.current,local,true);if(remote){setRemoteName(remote.user_name||"Other person");attach(remoteRef.current,remote,false)}};call.on("joined-meeting",()=>{setPhase("call");render();const local=call.participants().local;log(joinedOnce.current?"rejoined":"joined",{dailySessionId:local?.session_id||null});joinedOnce.current=true});call.on("participant-joined",render);call.on("participant-updated",render);call.on("participant-left",()=>{render();log("connection_interrupted",{who:"remote"})});call.on("track-started",render);call.on("network-connection",(e:any)=>{if(e.event==="interrupted"||e.networkState==="interrupted"){setNetwork("interrupted");log("connection_interrupted")}else if(network==="interrupted"){setNetwork("good");log("connection_recovered")}});call.on("network-quality-change",(e:any)=>{const state=e.networkState||"unknown";setNetwork(state);if((state==="bad"||state==="warning"||state==="low")&&reportedNetwork.current!==state){reportedNetwork.current=state;log(state==="bad"?"network_bad":"network_warning",{reasons:e.networkStateReasons||[]})}if(state==="good")reportedNetwork.current=""});call.on("error",(e:any)=>setError(e?.errorMsg||"Video connection error"));call.on("left-meeting",()=>{if(phase!=="ended")setPhase("preview")});await call.join({url:j.roomUrl,token:j.token,userName:j.displayName});}catch(e:any){setError(e.message);setPhase("preview")}}
 async function toggleCamera(){const next=!cameraOn;await callRef.current?.setLocalVideo(next);setCameraOn(next)}
 async function toggleMic(){const next=!micOn;await callRef.current?.setLocalAudio(next);setMicOn(next)}
 async function endCall(){await callRef.current?.leave();log("left");if(meeting&&Date.now()>=new Date(meeting.booking.endAt).getTime())await fetch(`/api/bookings/${bookingId}/complete`,{method:"POST"});setPhase("ended")}
 async function problem(eventType:string){const r=await fetch(`/api/bookings/${bookingId}/technical-event`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventType})});const j=await r.json().catch(()=>({}));setShowQuickProblem(false);if(r.ok)alert(`Problem recorded at ${new Date(j.recordedAt).toLocaleTimeString()}.`)}
 if(phase==="ended")return <section className="card session-ended"><h1>Session ended</h1><p>Your booking conversation remains available for the configured follow-up period.</p><a className="btn" href={`/bookings/${bookingId}`}>Back to booking</a></section>;
 if(phase==="preview"||phase==="joining")return <section className="waiting-room"><h1>Check your video</h1><div className="waiting-video"><video ref={previewRef} playsInline autoPlay muted/></div><div className="camera-checks"><span>{previewOk?"✓":"○"} Face visible</span><span>{previewOk?"✓":"○"} Hands visible</span><span>{previewOk?"✓":"○"} Upper body visible</span></div><p className="muted">Make sure your face, hands and upper body are clearly inside the frame.</p>{error?<p className="notice">{error}</p>:null}<button className="btn" disabled={!previewOk||phase==="joining"} onClick={join}>{phase==="joining"?"Joining…":"Join Session"}</button></section>;
 const secs=remaining??0;const beforeEnd=secs>0;const wrapSeconds=(meeting?.booking.wrapUpMinutes||2)*60;const display=beforeEnd?secs:Math.max(0,wrapSeconds+secs);const mm=Math.floor(display/60),ss=display%60;return <div className="call-shell"><div className="call-top"><strong>{remoteName}</strong><span className={`connection ${network}`}>{network==="good"?"Connection good":(network==="warning"||network==="low")?"Connection unstable":network==="bad"?"Poor connection":"Reconnecting…"}</span></div>{secs<=300&&secs>120?<div className="timer-banner">5 minutes remaining</div>:null}{secs<=120&&secs>0?<div className="timer-banner strong">⏱ {mm}:{String(ss).padStart(2,"0")} remaining</div>:null}{secs<=0?<div className="timer-banner strong">Session complete · {mm}:{String(ss).padStart(2,"0")} wrap-up</div>:null}<div className="video-stage"><video ref={remoteRef} autoPlay playsInline/><div className="local-video"><video ref={localRef} autoPlay playsInline muted/></div></div><BookingChat bookingId={bookingId} currentUserId={currentUserId}/><div className="call-actions"><button className="mini-btn" onClick={toggleCamera}>{cameraOn?"📹 Camera on":"📹 Camera off"}</button><button className="mini-btn" onClick={toggleMic}>{micOn?"🎙 Mic on":"🎙 Mic off"}</button><button className="mini-btn" onClick={()=>setShowDictionary(true)}>🔎 Dictionary</button><button className="mini-btn" onClick={()=>setShowQuickProblem(v=>!v)}>⚠ Problem</button><button className="mini-btn danger" onClick={endCall}>End</button></div>{showDictionary?<div className="dictionary-overlay"><DictionarySearch compact onClose={()=>setShowDictionary(false)}/></div>:null}{showQuickProblem?<div className="problem-menu"><strong>What's happening?</strong><button onClick={()=>problem("video_unclear")}>Video is unclear</button><button onClick={()=>problem("cannot_see_other")}>I cannot see the other person</button><button onClick={()=>problem("power_or_internet")}>Power / internet problem</button><button onClick={()=>problem("other")}>Other</button></div>:null}{error?<p className="notice">{error}</p>:null}</div>
}
